wx-minapp/minapp-vscode

src/plugin/lib/language.ts

add mpx language

---

src/plugin/getTagAtPosition/getWxmlTag.ts

fix(wxml): get wxml tag #34

---

src/plugin/WxmlAutoCompletion.ts
src/plugin/getTagAtPosition/getWxmlTag.ts

输入的时候自动触发typing 提示
```html
<view bi|继续提示bind
```
基于 #37

Feat autocomplete on typing

---

src/extension.ts
src/plugin/WxmlAutoCompletion.ts

```html
<image 
mode="aspectFill"↵
|回车后自动提示
></image>
```
<kbd>↵</kbd> 输入回车自动触发提示
字符前输入<kbd>空格</kbd>和<kbd>↵</kbd>不会触发自动提示
```html
<image [空格]|mode="aspectFill"/>
```

feat(enter): wxml enter  to provide auto completion

---

src/plugin/AutoCompletion.ts

除了`class=""`外
支持其他扩展样式名 如 `hover-class`等`xxx-class=""`组件传入样式名支持自动补全class name

feat(classname): xxx-class 自动补全class name

---

.github/workflows/deploy.yml

**解决了什么问题**:
Github Deploy CI失败了
**代码如何实现**:
更换secerts
**检查清单**:

chore: update github secrets

---

README.md

**解决了什么问题**:
README.md Logo和标题字体过大
**代码如何实现**:
改变大小
**检查清单**:

chore: down readme font-size

---

README.md

**解决了什么问题**:
Badge跳转链接错了
**代码如何实现**:
改成minapp-vscode的链接
**检查清单**:

fix: fix wrong badge link

---

README.md
package-lock.json
package.json

**解决了什么问题**:
更新Badge和插件名字(为了更好的搜索结果排名)
**代码如何实现**:
改md文件
**检查清单**:

chore: update README.md and change extension name

---

.eslintrc.js
package-lock.json
package.json
src/common/res/components.json
src/common/src/autocomplete.ts
src/common/src/custom.ts
src/common/src/dev/Component.ts
src/common/src/dev/components.ts
src/common/src/dev/config.ts
src/common/src/dev/index.ts
src/common/src/hover.ts
src/common/src/index.ts
src/common/src/lib/CacheableFile.ts
src/common/src/lib/ConditionalCacheableFile.ts
src/common/src/lib/fs.ts
src/common/src/lib/index.ts
src/common/src/mora/async.ts
src/common/src/parseAttrs.ts
src/plugin/AutoCompletion.ts
src/plugin/HoverProvider.ts
src/plugin/WxmlFormatter.ts
src/plugin/lib/language.ts
src/plugin/lib/requirePackage.ts
src/utils/noderequire.ts
src/wxml-parser/config.ts
src/wxml-parser/index.ts
src/wxml-parser/logParserError.ts
src/wxml-parser/parser.ts
src/wxml-parser/structs.ts
tsconfig.json

**解决了什么问题**:
将@minapp/common @minapp/wxml-parser相关代码提取出来，不再依赖相关包的版本发布
**代码如何实现**:
将npm源代码移到仓库中，方便迭代
**检查清单**:

chore: extract @minapp releative package

---

src/common/res/components.json
src/common/src/dev/components.ts
src/plugin/lib/language.ts
syntaxes/wxml.tmLanguage.json

**解决了什么问题**:
更新同步微信开发者文档元数据
**代码如何实现**:
更新components.json 和 wxml.tmLanguage.json文件
**检查清单**:

chore: update wxapp meta data

---

src/common/res/components.json
src/plugin/lib/language.ts

**解决了什么问题**:
补上老版本未添加的过去两年微信小程序新增的组件component，和a11y无障碍访问属性
**代码如何实现**:
更新Component.json和language.ts
**检查清单**:

chore: add new wx component and aria attrs

---

src/common/res/components.json
src/extension.ts

**解决了什么问题**:
同步微信官方组件元数据，提供代码补全
**代码如何实现**:
更新 components.json
**检查清单**:

chore: update wechat minprogram component metadata

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/feature_request.md

**解决了什么问题**:
增加`feature request` issue模板
**代码如何实现**:
**检查清单**:

chore: add feature request issue tpl

---

.github/ISSUE_TEMPLATE/feature_request.md

**解决了什么问题**:
typo
**代码如何实现**:
**检查清单**:

chore: fixtypo

---

CHANGELOG.md
package-lock.json
package.json
src/plugin/WxmlFormatter.ts
src/plugin/lib/config.ts

**解决了什么问题**:
fix  https://github.com/wx-minapp/minapp-vscode/issues/83#issuecomment-958626391
**代码如何实现**:
增加新的配置项
**检查清单**:

feat: add disableFormat config and upgrade component meta info

---

README.md
package.json

**解决了什么问题**:
重命名插件
```diff
- WXML - Language Services
+ WXML - Language Service
```
**代码如何实现**:
**检查清单**:

chore: rename extension brand

---

.eslintrc.js
src/extension.ts
src/plugin/WxmlFormatter.ts
src/plugin/lib/ScriptFile.ts

**解决了什么问题**:
优化定义跳转
**代码如何实现**:
兜底查找字符来获取定义位置
**检查清单**:

feat: improve jump definition

---

CHANGELOG.md
package-lock.json
package.json
src/extension.ts
src/plugin/WxmlDocumentHighlight.ts

**解决了什么问题**:
Try to fix #133
**代码如何实现**:
Revert deleted file
**检查清单**:

fix: regression issue of wxml pair tag highlight

---

README.md

**解决了什么问题**:
README 中基础的排版问题
**代码如何实现**:
无
**检查清单**:
无
支持一下 @iChenLei 的工作。

Optimize basic typesetting issues in README

---

.vscode/extensions.json
package-lock.json
package.json
src/plugin/WxmlAutoCompletion.ts

**解决了什么问题**:
增加赞助链接
**代码如何实现**:
**检查清单**:

chore: add sponsor link

---

.github/workflows/deploy.yml

**解决了什么问题**:
升级nodejs版本
**代码如何实现**:
**检查清单**:

chore: update deploy ci node version

---

.github/workflows/ci.yml
.github/workflows/deploy.yml
README.md
package-lock.json
package.json

**解决了什么问题**:
钉钉群二维码过期，项目存在依赖安全问题
**代码如何实现**:
更新二维码，更新项目依赖
**检查清单**:

chore: update dingding qrcode and deps
